version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGitMCSPDEV2507Project
  gitServerName: KusiMCSPDev
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.siqagitmcspdev2507.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBNewInsert
  packages:
  - name: SIQAGitMCSPDEV2507Project
    version: "1.0"
- serviceName: project.siqagitmcspdev2507.integrations:SIQAAdapterFlow
  packages:
  - name: SIQAGitMCSPDEV2507Project
    version: "1.0"
