version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGitMCSPDEV2507Project
  gitServerName: KusiMCSPDev
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
